name: Hello

on: 
  push: main
   
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: list files
        run: ls -ltra
      - name: run shell script
        run : 
          |
          chmod +x script.sh
          ./script.sh      