name: cowsee

on: push

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cowsay
        run: |
          sudo apt-get update
          sudo apt-get install cowsay  -y
      
      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
            name: dragon-file
            path: dragon.txt
            
      - name: Execute script
        run: |
          chmod +x script.sh
          ./script.sh